<#import "parts/common.ftlh" as c>
<#include "parts/security.ftlh">

<@c.page>
    <div class="jumbotron">
        <h1 class="display-4">Havach</h1>
        <p class="lead">This is a simple service food service unit, you do a click - we make food</p>
        <hr class="my-4">
        <p>Please, check our categories list</p>
        <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
    </div>
</@c.page>
