<div class="list-group ">
    <a href="/user/profile/" class="list-group-item list-group-item-action active">Dashboard</a>
    <a href="/user/profile/userlist" class="list-group-item list-group-item-action">User Management</a>
    <a href="/category" class="list-group-item list-group-item-action">Categories Management</a>
    <a href="/product/management" class="list-group-item list-group-item-action">Add Product</a>
</div>